// <auto-generated />
using System;
using ForestApp_CityApi_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForestApp_CityApi_DataAccess.Migrations
{
    [DbContext(typeof(CityApiDbContext))]
    partial class CityApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForestApp_CityApi_Entity.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 952, DateTimeKind.Utc).AddTicks(5308),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 952, DateTimeKind.Utc).AddTicks(8142),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 952, DateTimeKind.Utc).AddTicks(8249),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 952, DateTimeKind.Utc).AddTicks(8257),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 952, DateTimeKind.Utc).AddTicks(8262),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bursa"
                        },
                        new
                        {
                            Id = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 952, DateTimeKind.Utc).AddTicks(8270),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eskişehir"
                        });
                });

            modelBuilder.Entity("ForestApp_CityApi_Entity.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6d4b274-1d7e-4f56-a78a-100ad49200e5"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(32),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ayaş"
                        },
                        new
                        {
                            Id = new Guid("b07e8ecd-ea91-4986-8978-7f550ed59b80"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1621),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bala"
                        },
                        new
                        {
                            Id = new Guid("dafe0639-b8e4-4ecb-98f7-c1c454c443f1"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1660),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beypazarı"
                        },
                        new
                        {
                            Id = new Guid("daaf7086-09c8-48dd-92d4-f5eda6daf6e4"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1662),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çamlıdere"
                        },
                        new
                        {
                            Id = new Guid("776a0e54-f0d6-4322-ac85-28f5292c05a6"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1664),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çankaya"
                        },
                        new
                        {
                            Id = new Guid("af2cd559-dd78-422d-a820-0a4aede0b238"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1668),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çubuk"
                        },
                        new
                        {
                            Id = new Guid("6f85bdfd-cfcc-4773-889e-65ea673d47a1"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1670),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Elmadağ"
                        },
                        new
                        {
                            Id = new Guid("0300eafc-e9e4-44c2-8ebc-9c495cb8139e"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1672),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Güdül"
                        },
                        new
                        {
                            Id = new Guid("4e8ed2fa-ac91-4671-83f2-cd084a58aecf"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1673),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Haymana"
                        },
                        new
                        {
                            Id = new Guid("1ebc0ecf-886b-4432-9e8a-8158e2789816"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1682),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kalecik"
                        },
                        new
                        {
                            Id = new Guid("e68ebf9c-2f28-46a6-a078-1127995d5cb0"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1684),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kızılcahamam"
                        },
                        new
                        {
                            Id = new Guid("7d60310d-6eb2-4443-af9d-eb873680c9a1"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1685),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nallıhan"
                        },
                        new
                        {
                            Id = new Guid("7a097fd9-1503-474d-8e7c-f42eb6949a26"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1687),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Polatlı"
                        },
                        new
                        {
                            Id = new Guid("df38c5b5-ab63-46e4-a6b8-3924ee2f699f"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1689),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Şereflikoçhisar"
                        },
                        new
                        {
                            Id = new Guid("f42dc3f5-e1fa-4308-93b8-26c3f7300c59"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1690),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yenimahalle"
                        },
                        new
                        {
                            Id = new Guid("2afbc722-90d0-428d-8123-db822562de89"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1692),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gölbaşı"
                        },
                        new
                        {
                            Id = new Guid("c6c6335f-4cff-4595-bc9b-a2c742f9d2d6"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1694),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keçiören"
                        },
                        new
                        {
                            Id = new Guid("4e0356b1-10ad-495f-8b88-0c3fd88929e8"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1698),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mamak"
                        },
                        new
                        {
                            Id = new Guid("d007275c-ddd3-4a37-8f6f-780709683bba"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1700),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sincan"
                        },
                        new
                        {
                            Id = new Guid("29bbe05d-41a6-4d8f-93bb-e3f2a86e9e18"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1702),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kazan"
                        },
                        new
                        {
                            Id = new Guid("6f763cb0-6cd4-4d28-a8c0-160cefc6f4e5"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1703),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Akyurt"
                        },
                        new
                        {
                            Id = new Guid("7596fca5-469f-4028-aa4c-f26298dcb163"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1705),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Etimesgut"
                        },
                        new
                        {
                            Id = new Guid("2c9a20c1-85cb-440a-9c49-27ffcea49100"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1707),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Evren"
                        },
                        new
                        {
                            Id = new Guid("bba90293-8e5d-485b-9209-49f147b572a5"),
                            CityId = new Guid("5fa72a26-49a3-4d72-a5ce-e935c74ba887"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1708),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pursaklar"
                        },
                        new
                        {
                            Id = new Guid("495bb9c7-fdd6-440a-b2ee-fa68142e7402"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1716),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Akseki"
                        },
                        new
                        {
                            Id = new Guid("e17fdf4d-0968-4b7b-a2a8-82f7e8ff9f8b"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1720),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alanya"
                        },
                        new
                        {
                            Id = new Guid("7632c38e-2d70-4d71-9f69-a74aa890b024"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1722),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Elmalı"
                        },
                        new
                        {
                            Id = new Guid("ef45a9a8-a9d1-45bc-8701-8ba4ba304a0e"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1723),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Finike"
                        },
                        new
                        {
                            Id = new Guid("64954ce5-cda2-4b9d-8603-52a81bdf895c"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1725),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gazipaşa"
                        },
                        new
                        {
                            Id = new Guid("075773cb-562a-4cea-9cf9-77f50d162ab9"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1726),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gündoğmuş"
                        },
                        new
                        {
                            Id = new Guid("35ed1365-1071-4816-8997-c9e483ca76f5"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1728),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kaş"
                        },
                        new
                        {
                            Id = new Guid("4983b85d-5571-409d-bcf1-b1387f6e7d22"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1729),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Korkuteli"
                        },
                        new
                        {
                            Id = new Guid("bf03265b-b95e-4cb3-a3eb-62c828d5b36d"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1731),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kumluca"
                        },
                        new
                        {
                            Id = new Guid("ee19bbb4-10b9-4d33-9269-92104e5c17ee"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1736),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Manavgat"
                        },
                        new
                        {
                            Id = new Guid("86228c25-0ca1-4b25-bf3d-ece4eea2ad30"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1737),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Serik"
                        },
                        new
                        {
                            Id = new Guid("583944d6-4142-4a3b-a30f-25427e4c485e"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1783),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Demre"
                        },
                        new
                        {
                            Id = new Guid("17fdcc65-664d-4d45-a16f-13930d6c4ce9"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1785),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İbradı"
                        },
                        new
                        {
                            Id = new Guid("e37aaa8b-0fa9-4af2-ac3f-7213a45519d7"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1787),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kemer / Antalya"
                        },
                        new
                        {
                            Id = new Guid("30dac76c-cc05-49c4-b896-ba2044241a99"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1788),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aksu / Antalya"
                        },
                        new
                        {
                            Id = new Guid("91334eac-14a5-4139-831d-e63e26965ea9"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1790),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Döşemealtı"
                        },
                        new
                        {
                            Id = new Guid("5a25ba5b-b3d0-42e4-bee3-a8f006d0bcbf"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1791),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kepez"
                        },
                        new
                        {
                            Id = new Guid("a54d11b5-9ef2-4318-b612-a1430019506d"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1795),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Konyaaltı"
                        },
                        new
                        {
                            Id = new Guid("994b3096-928f-4de3-b42c-195130539daf"),
                            CityId = new Guid("f3a532cf-8321-4633-9bfd-10711e3a7aa8"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1796),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Muratpaşa"
                        },
                        new
                        {
                            Id = new Guid("3cb3d2dd-3d04-4f89-8832-71f429c072d0"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1798),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adalar"
                        },
                        new
                        {
                            Id = new Guid("59f6baa0-21c4-4b2f-86de-c83988026477"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1800),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bakırköy"
                        },
                        new
                        {
                            Id = new Guid("7faba713-a95f-4bbc-87eb-c16c19fc1c68"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1801),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            Id = new Guid("31bd3dd9-614e-4715-b156-daeaa6b35d9d"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1803),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beykoz"
                        },
                        new
                        {
                            Id = new Guid("cc1fe17a-8254-4c3f-8ecf-4057ec318e5d"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1804),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beyoğlu"
                        },
                        new
                        {
                            Id = new Guid("e63ad0d4-f1ee-47b3-85c0-bd044d2e333a"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1806),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çatalca"
                        },
                        new
                        {
                            Id = new Guid("8cf0c832-1126-4970-85a4-e5745df6f3c7"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1809),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eyüp"
                        },
                        new
                        {
                            Id = new Guid("9f6cd71d-3ed8-4af6-9217-4c36b996702b"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1810),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fatih"
                        },
                        new
                        {
                            Id = new Guid("e5969096-9e50-4e76-b447-77f8702328a3"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1812),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaziosmanpaşa"
                        },
                        new
                        {
                            Id = new Guid("e58d5c73-0a6b-4a1a-ba2a-6fd810aab465"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1813),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kadıköy"
                        },
                        new
                        {
                            Id = new Guid("ddaa99ab-a5d6-41d4-a859-2d115e9b254a"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1815),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kartal"
                        },
                        new
                        {
                            Id = new Guid("dad1049d-02bb-4d9f-9a89-e0bb0ab3273c"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1817),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sarıyer"
                        },
                        new
                        {
                            Id = new Guid("801de37a-ac0e-4071-98ea-5a0275b61e0b"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1818),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Silivri"
                        },
                        new
                        {
                            Id = new Guid("51ca42e9-5dcf-48b0-868d-b81ce045f8ba"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1820),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Şile"
                        },
                        new
                        {
                            Id = new Guid("22005864-8271-4d4e-ad1d-00629ac3538e"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1823),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Şişli"
                        },
                        new
                        {
                            Id = new Guid("235bd516-e109-4d29-9587-38031fa3b419"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1825),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Üsküdar"
                        },
                        new
                        {
                            Id = new Guid("fdc7594a-ab0c-465a-9043-67715e0791c7"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1826),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Zeytinburnu"
                        },
                        new
                        {
                            Id = new Guid("77b89944-efc4-4b6b-8a9e-1378302540e7"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1828),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Büyükçekmece"
                        },
                        new
                        {
                            Id = new Guid("a5d43e71-bfc7-468e-9eeb-7c4e9db8bc3f"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1829),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kağıthane"
                        },
                        new
                        {
                            Id = new Guid("60ef61c4-3372-42e7-b03a-deed7dcdeb62"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1831),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Küçükçekmece"
                        },
                        new
                        {
                            Id = new Guid("8beb7c40-c423-4207-9d96-18f685f02e45"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1832),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pendik"
                        },
                        new
                        {
                            Id = new Guid("1eee5e67-bc8a-4147-8c07-122c751c736d"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1834),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ümraniye"
                        },
                        new
                        {
                            Id = new Guid("978adb24-b6e1-414d-b3ad-cbaf14c9a112"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1838),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bayrampaşa"
                        },
                        new
                        {
                            Id = new Guid("669e579e-e2de-43dc-8a5e-a59c82a4a617"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1840),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Avcılar"
                        },
                        new
                        {
                            Id = new Guid("1a77093e-ce61-4f3b-8edb-0506d2a78900"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1841),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bağcılar"
                        },
                        new
                        {
                            Id = new Guid("3d7731e8-69c6-4950-a7d3-32012f902597"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1843),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bahçelievler"
                        },
                        new
                        {
                            Id = new Guid("15731cf8-365c-4a65-a028-9215b3b810e1"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1845),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Güngören"
                        },
                        new
                        {
                            Id = new Guid("13299cee-8f5c-478f-a105-9f11bbc0ed79"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1846),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maltepe"
                        },
                        new
                        {
                            Id = new Guid("b01d5263-b203-4a3c-adc4-2d8a5fc2928e"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1848),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sultanbeyli"
                        },
                        new
                        {
                            Id = new Guid("800b3adb-d96f-4512-b874-b90211a75a03"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1849),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = new Guid("2d04da86-4091-470b-a77f-2321c58eccc0"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1852),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Esenler"
                        },
                        new
                        {
                            Id = new Guid("295d89ae-f968-4b13-9c81-a0e1723a8d9f"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1854),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arnavutköy"
                        },
                        new
                        {
                            Id = new Guid("f4b28099-bac3-41b7-acf5-9332b817cce6"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1856),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ataşehir"
                        },
                        new
                        {
                            Id = new Guid("1fd0daec-166c-496d-ae3c-cf8cd6f3065a"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1857),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Başakşehir"
                        },
                        new
                        {
                            Id = new Guid("2566e714-b1b8-4f5a-a227-74c41606feca"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1859),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beylikdüzü"
                        },
                        new
                        {
                            Id = new Guid("be6c2724-7cb5-44ed-a217-185d6feb1762"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1860),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çekmeköy"
                        },
                        new
                        {
                            Id = new Guid("983f27ec-9c9d-4ada-ac2f-6a39925f18a6"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1862),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Esenyurt"
                        },
                        new
                        {
                            Id = new Guid("8a2927bd-533a-492d-8765-2c4dd583fe19"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1863),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sancaktepe"
                        },
                        new
                        {
                            Id = new Guid("a63ca900-8988-4cd3-9f9b-dd7c954e0052"),
                            CityId = new Guid("0e3921a6-e2f1-4492-8cdc-b36662c6fc74"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1867),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sultangazi"
                        },
                        new
                        {
                            Id = new Guid("d5a02456-79d3-43b1-aa18-51ba58562bf1"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1869),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aliağa"
                        },
                        new
                        {
                            Id = new Guid("d7aaacbd-b33f-45d3-a9e9-066a1926d71a"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1870),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bayındır"
                        },
                        new
                        {
                            Id = new Guid("19318782-66f0-4c21-b7b8-276d91522855"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1872),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bergama"
                        },
                        new
                        {
                            Id = new Guid("03ceccbf-512c-4e64-bc6d-33e5bac677be"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1873),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bornova"
                        },
                        new
                        {
                            Id = new Guid("79e9df48-25ef-42d5-9978-f5b5893978c9"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1875),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çeşme"
                        },
                        new
                        {
                            Id = new Guid("ed35c064-b6dd-4561-bc2e-2a440c4aa8f2"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1876),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dikili"
                        },
                        new
                        {
                            Id = new Guid("bacb6fa9-febe-488f-be6d-a12e68c6f055"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1878),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Foça"
                        },
                        new
                        {
                            Id = new Guid("8e1a8fed-776b-4afb-9522-2a840ef77157"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1881),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karaburun"
                        },
                        new
                        {
                            Id = new Guid("db96c1ea-0cd3-4e65-8e11-715a4225c31f"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1883),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karşıyaka"
                        },
                        new
                        {
                            Id = new Guid("55eaab1b-6002-4bef-91ed-21a6e5812193"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1884),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kemalpaşa / İzmir"
                        },
                        new
                        {
                            Id = new Guid("08f42f9c-5076-46a7-baf9-73691a2021a7"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1886),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kınık"
                        },
                        new
                        {
                            Id = new Guid("b9bcfe65-7946-43e2-ab74-fa2a2ee5a368"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1887),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kiraz"
                        },
                        new
                        {
                            Id = new Guid("9a341ee2-e108-4c02-ab76-04fb80b26664"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1889),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Menemen"
                        },
                        new
                        {
                            Id = new Guid("f32d96b0-4e1a-458d-aa0e-94bdd1e2b234"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1891),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ödemiş"
                        },
                        new
                        {
                            Id = new Guid("93e5d4c3-beb6-418e-afbc-75609bb0cd43"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1892),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Seferihisar"
                        },
                        new
                        {
                            Id = new Guid("4afcad6c-f6ac-4294-9034-8cd0bbb147da"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1896),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Selçuk"
                        },
                        new
                        {
                            Id = new Guid("26e3dfec-5600-4650-bdf4-ef33bb7781ac"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1897),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tire"
                        },
                        new
                        {
                            Id = new Guid("7ec2871f-1da3-4ab9-905b-d2d0c25be3bd"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1899),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Torbalı"
                        },
                        new
                        {
                            Id = new Guid("bc6dd89a-1371-4843-95ac-b6b9be61a7c1"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1900),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Urla"
                        },
                        new
                        {
                            Id = new Guid("ecd09611-be83-46f1-9261-68b2b04455ec"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1902),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beydağ"
                        },
                        new
                        {
                            Id = new Guid("d6ad0e84-6207-4125-9ae0-1536fc06cee9"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1903),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Buca"
                        },
                        new
                        {
                            Id = new Guid("12cad8bd-fb1a-453b-926f-1ce36374f9ee"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1905),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Konak"
                        },
                        new
                        {
                            Id = new Guid("fdd45586-2a40-4f52-9a1b-ebb56e906448"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1907),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Menderes"
                        },
                        new
                        {
                            Id = new Guid("e32ce81e-ec57-418e-ab83-3aff86becd60"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1910),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Balçova"
                        },
                        new
                        {
                            Id = new Guid("bffb7b88-13d9-44e6-9d9f-bc2d194a4d27"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1912),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çiğli"
                        },
                        new
                        {
                            Id = new Guid("b98b604f-c001-476e-992b-a3e1a91c6ab6"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1913),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaziemir"
                        },
                        new
                        {
                            Id = new Guid("d29c7c54-065d-4836-b312-6505e4c9407f"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1915),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Narlıdere"
                        },
                        new
                        {
                            Id = new Guid("d0d8d110-c00c-4172-aac4-c0556a963f09"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1949),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Güzelbahçe"
                        },
                        new
                        {
                            Id = new Guid("6f6312d4-6407-43a0-9596-935b180e34ba"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1951),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bayraklı"
                        },
                        new
                        {
                            Id = new Guid("ab6e57a1-b778-43b7-a6d6-961ee0136c8d"),
                            CityId = new Guid("fe3f958d-a55c-4e46-9126-a1a2a5b34674"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1952),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karabağlar"
                        },
                        new
                        {
                            Id = new Guid("8522aa5a-5ce7-465b-8ffb-be01eccd6e32"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1954),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gemlik"
                        },
                        new
                        {
                            Id = new Guid("37a55a3f-7414-40dd-82be-8f4e5b6cbfd1"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1958),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İnegöl"
                        },
                        new
                        {
                            Id = new Guid("d1804478-2d4a-4380-8489-acd4fc123916"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1959),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İznik"
                        },
                        new
                        {
                            Id = new Guid("8e562b36-4e6d-4a27-a185-abc880835115"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1961),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karacabey"
                        },
                        new
                        {
                            Id = new Guid("2ee293c6-9807-449c-84aa-a74171a820d4"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1962),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keles"
                        },
                        new
                        {
                            Id = new Guid("77c682c8-41de-4128-8367-cb20f2977c84"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1964),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mudanya"
                        },
                        new
                        {
                            Id = new Guid("c3396655-a6ea-4d6d-adb1-666e0ceeba8f"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1965),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mustafakemalpaşa"
                        },
                        new
                        {
                            Id = new Guid("b21755f4-38ba-4f84-93f3-47d6510be4e8"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1967),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orhaneli"
                        },
                        new
                        {
                            Id = new Guid("543345fc-2ec6-4632-983f-14c73552e3d7"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1968),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orhangazi"
                        },
                        new
                        {
                            Id = new Guid("25f97d04-03d7-4561-a0f7-c4239eaa905e"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1972),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yenişehir / Bursa"
                        },
                        new
                        {
                            Id = new Guid("722362f5-e38a-400a-b973-ef1f3d238e4b"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1973),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Büyükorhan"
                        },
                        new
                        {
                            Id = new Guid("cec2cc85-2257-44e9-8161-99c4839eeddd"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1975),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Harmancık"
                        },
                        new
                        {
                            Id = new Guid("d0929799-8d4d-4617-9609-7e549f2d3f72"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1976),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nilüfer"
                        },
                        new
                        {
                            Id = new Guid("78725269-2a73-45be-8f05-84490d65b057"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1978),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Osmangazi"
                        },
                        new
                        {
                            Id = new Guid("261e9970-0256-497b-b914-7d0c8c2adf81"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1979),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yıldırım"
                        },
                        new
                        {
                            Id = new Guid("1de12185-f74c-4d2d-96ff-f51a5847f33f"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1981),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gürsu"
                        },
                        new
                        {
                            Id = new Guid("aa7ce1ed-881e-4d55-825a-4e193c7bf516"),
                            CityId = new Guid("ffc28b74-9be7-41ac-8759-60baf56988ee"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1982),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kestel"
                        },
                        new
                        {
                            Id = new Guid("7e5e2030-fef5-4feb-a9c6-ec77d0a7591c"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1988),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çifteler"
                        },
                        new
                        {
                            Id = new Guid("b347170a-bad7-4db2-9522-8372bad4a65c"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1989),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mahmudiye"
                        },
                        new
                        {
                            Id = new Guid("f681a4cb-35d4-485f-bbe8-71d3ffbf1315"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1991),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mihalıççık"
                        },
                        new
                        {
                            Id = new Guid("c02df84a-a50b-4b8f-b30d-2a082c89f317"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1992),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sarıcakaya"
                        },
                        new
                        {
                            Id = new Guid("c6b3a4cf-a992-47ea-a5d6-edd12eb189a0"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1994),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Seyitgazi"
                        },
                        new
                        {
                            Id = new Guid("1e82fe45-af85-481a-925a-5bc762142f6f"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1996),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sivrihisar"
                        },
                        new
                        {
                            Id = new Guid("22e1fc98-4dd8-4f77-ad1c-6afcf7c3485f"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1997),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alpu"
                        },
                        new
                        {
                            Id = new Guid("cdda3ddd-88ec-4283-be87-00594c8e4818"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(1999),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beylikova"
                        },
                        new
                        {
                            Id = new Guid("e8147ac7-f27d-4b7d-a00b-a123a236b71e"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(2002),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İnönü"
                        },
                        new
                        {
                            Id = new Guid("c1411014-69fb-41db-b72a-d617c486f43c"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(2003),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Günyüzü"
                        },
                        new
                        {
                            Id = new Guid("e013d037-0f4c-420f-a8b3-ac44a0365e70"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(2005),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Han"
                        },
                        new
                        {
                            Id = new Guid("3fe1ca22-5a7e-4135-a960-c6120d7cc4e7"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(2007),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mihalgazi"
                        },
                        new
                        {
                            Id = new Guid("ea5c56f4-3bc3-45b1-9ddf-c38c945e587f"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(2008),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Odunpazarı"
                        },
                        new
                        {
                            Id = new Guid("d01e3cb9-8340-4894-b00b-10e359f922d4"),
                            CityId = new Guid("6555fbc4-d38a-44dd-955f-3d81db6c536a"),
                            CreatedOn = new DateTime(2021, 2, 12, 7, 39, 15, 954, DateTimeKind.Utc).AddTicks(2010),
                            LastAccessed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tepebaşı"
                        });
                });

            modelBuilder.Entity("ForestApp_CityApi_Entity.District", b =>
                {
                    b.HasOne("ForestApp_CityApi_Entity.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
